Add support for encoding multiple properties with the same key
jordic/goics pull request #14
Opened 2021-03-24 17:52 UTC by harrisonhjones

**Motivation**

I am trying to add multiple `ATTENDEE` properties to a `VEVENT` components. I realized that I couldn't (easily) do this using the `AddProperty` method. In my opinion it should have been called `SetProperty` but that could come in another PR. This update changes the way `AddProperty` works to make it a true "add" and not a "set".

**Changes**

1. Updated `AddProperty` to act like a true "add" operation instead of a "set" operation.
1. Updated the tests to check for this new behavior.
1. Formatted the project with `gofmt` which added a _bit_ of noise to the diff.

2021-03-31 10:25 UTC, jordic requested changes
Seems fair to merge this, but can you clean up cosmetic changes (Changes on the changeset not related to the PR)?

2021-03-31 10:25 UTC, jordic commented on decoder.go
> +
Sorry, can you cleanup cosmetic changes (Changes not related to the PR)

2021-04-01 01:44 UTC, harrisonhjones commented
I just finished cleaning up the PR. Let me know if this works for you now.

2021-04-01 01:48 UTC, harrisonhjones commented
Moved the formatting changes to https://github.com/jordic/goics/pull/15

2021-04-04 17:46 UTC, merged

2021-04-04 17:46 UTC, jordic commented
So many thanks for your contribution!